merging changes from branch/multijunk

diff --git a/trunk/src/runScenarios b/trunk/src/runScenarios
--- a/trunk/src/runScenarios
+++ b/trunk/src/runScenarios
@@ -2,9 +2,34 @@
 stamp=`date "+%d/%m/%y %H:%M:%S"`" $1"
 echo "$stamp runScenarios"
 echo "$stamp runScenarios" >> log
-runs=3;
+
+function help
+{
+	echo "Syntax: ./runScenarios \"[path to scenario files]\" \"[args to pass hog]\" [number of runs]"
+	echo "Example: ./runScenarios \"experiments/scenarios/local/*\" \"-search jps\" 3"
+	echo "NB:"
+	echo "Quotation marks are important. Don't omit them!"
+	echo "It may also be necessary to append the wildcard character * to the end of "
+	echo "the path if every file in the target directory is a scenario"
+}
+
+if [ $# -le 1 ]
+then
+	echo "Error: Invalid syntax. $0 $1 $2 $3"
+	help
+	exit 1
+fi
+
+runs=
+if [ -n "$3" ]
+then
+	runs=$3
+else
+	runs=1
+fi
+
 for ((x=1;x<=$runs;x++)) ; do
-	for i in $(ls $1*.map.scen*);
+	for i in $(ls $1);
 	do
 			echo "$i"
 			./bin/hog -scenario $i -nogui $2 >> log
@@ -17,3 +42,4 @@ for ((x=1;x<=$runs;x++)) ; do
 			fi
 	done
 done
+
